# fly.toml app configuration file generated for movieapplication on 2024-02-21T12:46:51-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movieapplication'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
